version: "2.1"
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - .env
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  web:
    build: .
    ports:
        - 8000:8000
    volumes:
        - .:/code
    command: [ 'sh', '-c',
        'until curl http://${RABBITMQ_USER}:${RABBITMQ_USER}@rabbitmq:15672/api/aliveness-test/%2F;
        do echo waiting for rabbitmq; sleep 2; done; 
        uvicorn api:app --host 0.0.0.0 --port 8000 --reload'
        ]
    depends_on:
        - rabbitmq

  listener:
      build: .
      volumes:
          - .:/code
      command: [ 'sh', '-c',
        'until curl http://guest:guest@rabbitmq:15672/api/aliveness-test/%2F;
        do echo waiting for rabbitmq; sleep 2; done; 
        python listener.py',
        ]
      depends_on:
          - rabbitmq
          - web
